### ISSUE TITLE
build: error finding git.apache.org/thrift.git

### ISSUE THREAD

**Issue by alx** [go-chat-bot/bot#115]
Hi,

I'm not sure how to debug this issue on my side, I'm just trying to build everything in order to build a new bot (it might not be the best practice), and this process blocks on this error:

```
$ go build ./...
go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/alx/go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
        fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out
go: error loading module requirements
```

Thanks,

Alex

**Comment by fabioxgn** [comment]
@alx which version of go are you using? I was having this error on circle ci and updating to go 1.13 solved it.

**Comment by alx** [comment]
I was using `1.12`:

```
$ go version                                                                                                                                                                                                   
go version go1.12.9 linux/amd64
```

I've upgraded to `1.13` - https://github.com/golang/go/wiki/Ubuntu - but still have the same error.

```
$ go version
go version go1.13 linux/amd64
```

I've already tried to delete the repository and clone it again, should I try something else ?

**Comment by fabioxgn** [comment]
@alx I've updated the dependecies. Looks like that the google cloud package was depending on this package, but now its gone. Please, get the lastest version of the master branch and try again.

**Comment by alx** [comment]
Thanks @fabioxgn , it's building now.

Have a nice  day,

Alex
