### ISSUE TITLE
Expand with PeriodicCommands?

### ISSUE THREAD

**Issue by aspic** [go-chat-bot/bot#14]
Hi, and thanks for this neat little bot! Sorry to open an issue but I wanted a place to discuss a little feature I've been thinking about. It's basically a new type of command 'PeriodicCommands' (a better name is welcome), which are commands run after some duration, or at a specific time (like a cron job).

My use case for this would be checking some logs every X minute, and if some error occurs, post a message to the provided channel/user.

The easiest way to accomplish this would be to add this new type of commands, as well as a RegisterPeriodicCommand function (similar to RegisterCommand). And in the loop check whether or not to run any of these periodic commands. Do you have any thoughts or different ideas to achieve the same goal? :-) I would be happy to code up a PR if you think this is something we should add to the bot.

- Kjetil

**Comment by fabioxgn** [comment]
Hi @aspic I like this idea. This command would have to be somewhat different from the normal commands, as you would have to pass some configs to it like, the interval for it to run and which channel to post messages, so I guess it should not be registered on initialization, some psude code about how I image it:

```
config := PeriodicConfig {
  Period: 5 * time.Second,
  Channel: "#go-bot",
}
bot.RegisterPeriodicCommand(config, func (string, err))
```

This func would be called every 5 seconds, if it returns some text it would be sent to the `#go-bot` channel.

Is your idea something like it?

**Comment by aspic** [comment]
Yup, exactly like that, except Channel is a slice of Channels. There is a little library for scheduling tasks in go (https://github.com/jasonlvhit/gocron) that might be useful. :-)

**Comment by aspic** [comment]
I added a small example with tickers and one with a cron library: https://github.com/aspic/bot/commit/df6873d7826d531cbb7502c69bcb66cfb72e3ecf

I fully understand if you don't want to depend on another library in bot.go (https://godoc.org/github.com/robfig/cron), but using it avoids cluttering bot.go with a lot of custom time-parsing and channel handling.

The config could be something like: 
```config := &bot.PeriodicConfig{CronSpec: "@every 2s", Channels: []string{"#channel"}}```

**Comment by fabioxgn** [comment]
@aspic nice. I don't have any problems with the external dependency, it will be more flexible and extensive in the end. :shipit:

**Comment by aspic** [comment]
Ait, I will code up a proper PR as soon as I find the time :-)

**Comment by aspic** [comment]
This issue/feature request is closed with https://github.com/go-chat-bot/bot/pull/15
