### ISSUE TITLE
Slack - Get the channel name

### ISSUE THREAD

**Issue by dgil** [go-chat-bot/bot#32]
First, thanks for open sourcing this chat bot!

I'm working on a small bot that connects to our Slack, but I don't know how to get the channel name. Currently I only get the `user` (nickname and name), `channel` (id) and the `command`. 

Is there any way to get the channel name?

**Comment by fabioxgn** [comment]
Hello @dgil thanks for using it :)

Currently there is no way to get the channel name from the bot, it would require a new call to the Slack's API, as the [message event](https://api.slack.com/events/message) just return the `channel_id` so to get channel name we would need to make an extra call to [channels.info method](https://api.slack.com/methods/channels.info).

I could implement that, but what's your use case for this? Why do you need the channel name on the command?

**Comment by dgil** [comment]
Hey @fabioxgn, thanks for your answer. I was wondering if supporting the channel name could make easier to setup the bot, but at the end I did what you mention: get the `channel_id` from slack's API.

I don't think you need to implement anything, it's easy to do 😄
