### ISSUE TITLE
General debug mode

### ISSUE THREAD

**Issue by kiliankoe** [go-chat-bot/bot#36]
Hi, I'm currently trying to migrate a [hubot](https://hubot.github.com) powered slackbot away from its underlying hubot (getting tired of writing coffeescript and using node).

One thing I'm kinda missing from hubot is the local debug mode. Hubot bundles an executable that starts a local instance of the bot completely inside the shell where the user can interact with the bot trying out various functionality and debugging plugins. For testing purposes, this "room" is visible to both the user and the bot as "#shell" with the user also being called "shell" by the bot. 

Integrating something along the lines of that here should probably result in a new adapter or protocol as you call it in `/debug` possibly? I'm not really versed yet in all things go but would love to try myself at creating a PR for a feature like that. Any possible input would be greatly appreciated though!

**Comment by fabioxgn** [comment]
Hi @kiliankoe nice idea.

I think the easiest way to implement this is to create a console app, maybe a subpackage named console and then we can just compile it and run from the comand line like:

```
$ ./bot !help
Type: '!help <command>' to see details about a specific command.
Available commands: gif, puppet, cnpj, cotacao, decode, encode, guid, megasena, treta, catgif, cpf, crypto, godoc

$ 
```

it would be very easy to implement. I'll try to do it if I can find some free time.
