### ISSUE TITLE
IRC: Missing RealName on events

### ISSUE THREAD

**Issue by doenietzomoeilijk** [go-chat-bot/bot#39]
I'd like to use go-chat-bot for IRC purposes, but I'm running into a snag. I can solve the snag, but I'm looking for some input on the best way to solve it.

The issue I'm running into is the fact that in `irc/irc.go`, on a privmsg event, the User is created with only his nick. If I want some command to be limited to certain user/host combo's, I'm out of luck, since I only have the nick to work with. As I see it, there's three ways of solving it:

* Stuff the username/host into `User.RealName`. This works, but it's slightly ugly since we're stuffing something that's not a RealName into a RealName.
* Add host info to the User, for example `User.Host`. I'm not sure how that'd impact other networks, if at all. I don't know if you get that kind of info from Slack / Telegram, and whether they make any sense there. Still, this seems like the best solution to me.
* Do an IRC whois inside my command to validate the user. This would work (assuming I can do that from within the bot, I haven't looked into it that much), but it's wasteful as it results in more IRC traffic on each request. Last-ditch resort, I'm really not a fan of this one.

I think the second option would be the best one; it'd involve adding some properties to `User` that might go unused for non-IRC networks - I don't think that's a huge problem, but input on this would be welcome.

I can come up with a pull request, of course.

**Comment by doenietzomoeilijk** [comment]
I've done a little digging, and both Telegram and Slack have a user ID for every user - Slack can have an e-mail address too, sometimes, but it's not a given.

I propose to add an ID field to the User struct, which gets filled with user ID for Slack and Telegram, and `user@host` for IRC. This gives you a unique identifier on all three networks.

I'll come up with a PR soon-ish.

**Comment by fabioxgn** [comment]
@doenietzomoeilijk hi, thanks for the interest in this project. Using the ID for me looks go enough, go for it :)
