### ISSUE TITLE
Multi-line response from plugin

### ISSUE THREAD

**Issue by reestr** [go-chat-bot/bot#48]
Is there any way to return a multi-line response from a plugin?  Currently if I put a newline in the string then only the first line displays:
`msg = fmt.Sprintf("Can we do\nmulti line return?")`

**Comment by fabioxgn** [comment]
IRC protocol? Because IRC does not support multi line message.

I guess that just spliting the message here and sending multiple messages will solve it:

https://github.com/go-chat-bot/bot/blob/master/irc/irc.go#L36

**Comment by reestr** [comment]
Thanks for the heads up, I have sent PR #49
