### ISSUE TITLE
Telegram api error exit status 1

### ISSUE THREAD

**Issue by romanornr** [go-chat-bot/bot#57]
````
package main

import (
    "os"
    "github.com/go-chat-bot/bot/telegram"
)

func main() {
    telegram.Run(os.Getenv("telegram__tokenhere"), os.Getenv("DEBUG") != "")
}
````
The result I received is:
````2017/07/27 02:04:52 Not Found
exit status 1
````
My api token is working on other frameworks.

**Comment by fabioxgn** [comment]
@romanornr if you pass the second parameter as `true`, does it print out any other info?

**Comment by romanornr** [comment]
Not sure what you mean.
Can you type the line in here?

**Comment by fabioxgn** [comment]
@romanornr I think I know what you are doing wrong, notice that in the example you don't put the telegram token in the code, instead you put it in a environment variable and use the variable in the code.

Try this just to see if it works:

```
telegram.Run("telegram__tokenhere", true)
```
