### ISSUE TITLE
Getting two responses for single slack command

### ISSUE THREAD

**Issue by dwdraju** [go-chat-bot/bot#69]
I am building slack bot which basically takes kubectl command like `kubectl get pods`. Now, I want to send some message like `Your request has been acknowledged` immediately after any command is sent from slack and then the result of command. Currently, I have implemented the command result sending process but couldn't figure out how to send the "pre result message". Any idea? I tried implementing this way:
```
func response(command *bot.PassiveCmd) (string, error) {
   return fmt.Sprintf("Your request has been added to queue"), nil
}
func init() {
	bot.RegisterPassiveCommand(
					"",
					response)
}
func init() {
	bot.RegisterCommand(
 		"deployer",
 		"Kubectl Slack integration",
 		"",
	kubectl)
 
}
```

But the problem is when I enter slack message with `@deployer get pods`, then it triggers `kubectl` and when I just hit `kubectl get pods`, it triggers `response`. But I need to combine both. PS: Here, my cmdprefix is `@`. Hope you get it. If I am not clear, please feel free to ask on comment. Thanks.

**Comment by toolateforteddy** [comment]
If you are ok with using `@deployer get pods` then you can register it as a V3 command which allows you to send multiple messages over time by writing them to a channel.

Otherwise, we can extend the passive command framework to offer a V3 equivalent. I can look into that this weekend.

**Comment by toolateforteddy** [comment]
https://github.com/toolateforteddy/bot/blob/master/cmd.go#L175

Proposal for you. What do you think?

**Comment by dwdraju** [comment]
Sorry, but I am still not getting it. Here is how I tried:

```
func kubectl(command *bot.Cmd) (msg string, err error) {
.....
return fmt.Sprintf(okResponse, nickname, output), nil
}

func cmdV3(command *bot.PassiveCmd) (result bot.CmdResultV3, err error) {
	result = bot.CmdResultV3{
	Channel: "#channel",
	Message: make(chan string),
	Done:    make(chan bool)}
fmt.Println("hello")
return result, nil
}

func init() {
bot.RegisterPassiveCommandV2(
		"",
		cmdV3)
		bot.RegisterCommand(
		"deployer",
		"Kubectl Slack integration",
		"",
		kubectl)
}
```

**Comment by fabioxgn** [comment]
@dwdraju if I understood correctly, the problem is that you are not writing on the Message channel.

for the V3 command to work properly you need to start a go routine to do the long running work and return the CmdResultV3 imediatelly, try something like this:

```Go
func cmdV3(command *bot.PassiveCmd) (result bot.CmdResultV3, err error) {
	result = bot.CmdResultV3{
        Channel: "#channel",
        Message: make(chan string),
        Done: make(chan bool)}

    result.Done <- false

    go func() {
        result.Message <- "Starting heavy work..."
        ... do your stuff
        result.Message <- "Heavy work done... time to grab a beer."
        result.Done <- true
    }()

    return result, nil
}
```

I did not test this code so the syntax might be wrong.

**Comment by dwdraju** [comment]
@fabioxgn, did that way and it works but can we add `Args  []string` on `PassiveCmd` as well like on `Cmd`. I was doing like this:
```
func kubectl(command *bot.Cmd) (msg string, err error) {
......
output := execute("kubectl", command.Args...)
......
}
```
And it was working well. Now, I tried like below for passive cmd:
```
func cmdV3(command *bot.PassiveCmd) (result bot.CmdResultV3, err error) {
.......
go func() { 
		result.Message <- "ping" 
		output := execute("kubectl", command.MessageData.Text)
		result.Message <- output
		result.Done <- true
	}()
......
```
Here is `execute`:
```

func execute(name string, arg ...string) string {
	rescueStdout := os.Stdout
	r, w, _ := os.Pipe()
	os.Stdout = w
	os.Stderr = w

	cmd := exec.Command(name, arg...)

	stdin, err := cmd.StdinPipe()

	if err != nil {
		fmt.Println(err)
	}

	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err = cmd.Start(); err != nil {
		fmt.Println("An error occured: ", err)
	}

	stdin.Close()
	cmd.Wait()

	w.Close()
	out, _ := ioutil.ReadAll(r)
	os.Stdout = rescueStdout

	return string(out)
}
```


Now, the problem is, as I am using string `command.MessageData.Text`, the `cmd := exec.Command(name, arg...)` is working like: `kubectl 'get pods'`(with single quote) if I pass `get pods` via slack. I think adding `Args        []string` could solve this.



I might sound off topic, but anyway help would be highly appreciated. Thanks.

**Comment by fabioxgn** [comment]
@dwdraju why are you using `command.MessageData.Text` did you try using `command.RawArgs` like here?
https://github.com/go-chat-bot/plugins/blob/master/cmd/cmd.go#L32
