### ISSUE TITLE
Add new command type: filter

### ISSUE THREAD

**Issue by sochotnicky** [go-chat-bot/bot#78]
So I have 2 use cases that would need new type of command. 

Use cases: 
 * When URLs are posted by the bot automatically use shortener on them
 * Provide ability to silence the bot for period of time in specific channel

The way I imagine this working is as follows:
 * Add a new "filter" command registration
 * Filters get called around/inside SendMessage invocations

They can either "skip" the message (second use case) or modify the output (first use case). It seems like a nicer approach then for example implementing shortener in JIRA and/or other plugins.

Thoughts?

**Comment by sochotnicky** [comment]
I see for example this could be simplified as well with the shortener filter:
https://github.com/go-chat-bot/plugins/blob/master/gif/gif.go

**Comment by fabioxgn** [comment]
If I understood it correctly, these filters will filter other commands output, is that it?

I think it's a nice idea.

**Comment by sochotnicky** [comment]
Yeah, that is the idea - you could create "silence" plugin that would let people say "!silence 5m" and for 5 minutes no messages would be output in the channel for example. Right now that's not possible

As with the other pieces - I can make the initial proposal/changes though no clue when I'll get to it yet :-)

**Comment by sochotnicky** [comment]
FWIW maybe it's worth noting somewhere the filters have no guaranteed order in which they get run. Not sure that matters...
