### ISSUE TITLE
cannot use message (type string) as type slack.MsgOption in argument to api.PostMessage

### ISSUE THREAD

**Issue by lanybass** [go-chat-bot/bot#92]
https://github.com/go-chat-bot/bot/blob/cf98806022032f1199b8e612483a21485156b169/slack/slack.go#L32

`D:\Go\GOPATH\src\github.com\go-chat-bot>go build ./...
# github.com/go-chat-bot/bot/slack
bot\slack\slack.go:32:17: cannot use message (type string) as type slack.MsgOption in argument to api.PostMessage
bot\slack\slack.go:32:17: cannot use params (type slack.PostMessageParameters) as type slack.MsgOption in argument to api.PostMessage`

**Comment by dberuben** [comment]
same issue for me 
`# github.com/go-chat-bot/bot/slack
../github.com/go-chat-bot/bot/slack/slack.go:32:17: cannot use message (type string) as type slack.MsgOption in argument to api.PostMessage
../github.com/go-chat-bot/bot/slack/slack.go:32:17: cannot use params (type slack.PostMessageParameters) as type slack.MsgOption in argument to api.PostMessage`

**Comment by Issif** [comment]
same error 

```
src/github.com/go-chat-bot/bot/slack/slack.go:32:17: cannot use message (type string) as type slack.MsgOption in argument to api.PostMessage
src/github.com/go-chat-bot/bot/slack/slack.go:32:17: cannot use params (type slack.PostMessageParameters) as type slack.MsgOption in argument to api.PostMessage
```

**Comment by Skarlso** [comment]
@lanybass @dberuben What version of Go are you guys using? I just tried it and seems to be working fine. I was able to build the project. @Issif.

**Comment by yitsushi** [comment]
The repo uses gomod with pin on github.com/nlopes/slack v0.4.0

**Comment by Skarlso** [comment]
The version of https://github.com/go-chat-bot/bot/blob/master/slack/slack.go is not the right version in the go mod file.

**Comment by dberuben** [comment]
i'm using go version go1.11.2 darwin/amd64

**Comment by sciffer** [comment]
The golang version is not the issue, just pin nlopes slack to v0.4.0.
go to that folder "cd $GOPATH/src/github/nlopes/slack" and run "git checkout tags/v0.4.0"
After that you can compile the gobot without any issues

**Comment by qlikcoe** [comment]
Just FYI, you now have to use `v0.5.0` of `/nlopes/slack' after this was commited: 
https://github.com/go-chat-bot/bot/commit/e13ffd51259d5d03b94a6e6f1fb61f25390397c1#diff-c25033a972715dbbdb7e73ac79261230
